#!/bin/bash

cp -fr ~/.bashrc _bashrc
cp -fr ~/.clang-format _clang-format
cp -fr ~/.doom.d _doom.d
cp -fr ~/.spacemacs _spacemacs
cp -fr ~/.SpaceVim.d _SpaceVim.d
cp -fr ~/.vimrc _vimrc
cp -fr ~/.xbindkeysrc _xbindkeysrc
cp -fr ~/.zsh.d _zsh.d

