#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "wave"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "default"

[[layers]]
    name = "foldsearch"

[[layers]]
  name = "lang#c"
  format_on_save = true
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
  libclang_path = "/usr/lib/libclang.so"
  [layer.clang_std]
    c = "c18"
    cpp = "c++20"

[[layers]]
  name = "lang#python"
  format_on_save = false
  enabled_linters = ['python', 'pylint']

[[layers]]
    name = 'lang#javascript'
    format_on_save = true

[[layers]]
    name = "lang#r"
    repl_command = "R"

[[layers]]
  name = "lang#rust"
  recommended_style = true
  format_on_save = true


[[layers]]
  name = "lsp"
  filetypes = [ "c", "cpp", "python", "rust"]
  enabled_clients = ["pyright", "clangd", "rustup"]
  [layers.override_cms]
    rust = ["rustup", "run", "nightly", "rust-analyzer"]

