function prompt_histno() {
  typeset -g POWERLEVEL9K_HISTNO_BACKGROUND=#1155bb
  typeset -g POWERLEVEL9K_HISTNO_FOREGROUND=#eeee55
  typeset -g POWERLEVEL9K_HISTNO_ICON=$'\U2762'

  p10k segment -b $POWERLEVEL9K_HISTNO_BACKGROUND -f $POWERLEVEL9K_HISTNO_FOREGROUND -i $POWERLEVEL9K_HISTNO_ICON -t "${HISTCMD:-0}"
}

